FROM node:8

# create working directory

WORKDIR /app

# Install dependencies

COPY package.json /app

RUN apt-get update && \
    apt-get install -y sox && \
    npm install

COPY . /app

EXPOSE 3000

CMD [ "npm", "start" ]